version: "3.7"

services:
  unit:
    build:
      context: ..
      dockerfile: src/Dockerfile
      target: test
    volumes:
      - ../src:/home/user/src

  integration:
    build:
      context: ..
      dockerfile: src/Dockerfile
      target: test
    volumes:
      - ../src:/home/user/src
