name: Code Integration

on:
  push:
    branches:
      - 'main'
      - 'fix-docker'

jobs:
  test:
    name: Run the test suite
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run the tests
        run: make test
